update helper.js due to many-to-many associations fails on update
 return hop.call(obj, prop);
             ^
TypeError: Cannot convert null to object
    at hasOwnProperty (native)